// ============================================================================
// MbaUtils.cpp — MBA factory implementation
//
// All per-opcode transforms, advanced inflation helpers, and STATISTIC counters
// previously living inside the anonymous namespace of MBAObfuscation.cpp are
// collected here so that both MBAPass and VMPass can share them without
// duplication.
// ============================================================================

#include "llvm/Transforms/Obfuscator/MBAUtils.h"
#include "llvm/Transforms/Obfuscator/Rng.h"
#include "llvm/Transforms/Obfuscator/Utils.h"

#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/LineIterator.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"

// Compiled-in fallback SLE pool (generated by utils/mba_sle_gen.py).
#include "llvm/Transforms/Obfuscator/MBASlePool.inc"

#include <algorithm>
#include <cstdlib>
#include <string>
#include <vector>

using namespace llvm;
using namespace llvm::obf;

#define DEBUG_TYPE "mba"

// ============================================================================
// Statistics  (moved from MBAObfuscation.cpp)
// ============================================================================

STATISTIC(MBAAdd, "Add instructions transformed with MBA");
STATISTIC(MBASub, "Sub instructions transformed with MBA");
STATISTIC(MBAAnd, "And instructions transformed with MBA");
STATISTIC(MBAOr, "Or  instructions transformed with MBA");
STATISTIC(MBAXor, "Xor instructions transformed with MBA");

// ============================================================================
// Construction
// ============================================================================


MbaUtils::MbaUtils(Module& M, Rng& R, StringRef SlotName)
	: MbaUtils(M, R, SlotName, Options{}) {
}


MbaUtils::MbaUtils(Module& M, Rng& R, StringRef SlotName, Options Opts)
	: M(M), R(R), SlotName(SlotName), Opts(Opts) {
}

// ============================================================================
// Opcode filter
// ============================================================================

bool MbaUtils::isTargetOpcode(unsigned Op) {
	return Op == Instruction::Add || Op == Instruction::Sub ||
		Op == Instruction::Xor || Op == Instruction::And ||
		Op == Instruction::Or;
}

// ============================================================================
// Per-function noise slot management
// ============================================================================

AllocaInst* MbaUtils::ensureNoiseSlot(IRBuilder<>& B) {
	Function* Fn = B.GetInsertBlock()->getParent();
	if (CachedFn == Fn && NoiseSlot)
		return NoiseSlot;

	// Switch to the new function — reset cached state.
	CachedFn = Fn;
	NoiseSlot = nullptr;

	// Pin the entropy anchor first (must precede the noise slot in entry block).
	(void)llvm::obf::ensureEntropyAllocaAtEntryBegin(*Fn);

	NoiseSlot = llvm::obf::getOrCreateVolatileI32Slot(*Fn, SlotName, R);
	return NoiseSlot;
}

AllocaInst* MbaUtils::getOrCreateNoiseSlot(IRBuilder<>& B) {
	return ensureNoiseSlot(B);
}

// ============================================================================
// Poison-sensitive flag check
// ============================================================================

bool MbaUtils::hasPoisonSensitiveFlags(const BinaryOperator& BO)
{
	// For correctness: don't change poison behavior of flagged ops.
	// Add/Sub can carry nuw/nsw; skip those sites.
	switch (BO.getOpcode()) {
	case Instruction::Add:
	case Instruction::Sub:
		return BO.hasNoSignedWrap() || BO.hasNoUnsignedWrap();
	default:
		return false;

	}
}

// ============================================================================
// Core Value-level transforms — Add
// ============================================================================

// x + y  =>  (x ^ y) + 2*(x & y)
Value* MbaUtils::add(IRBuilder<>& B, Value* A, Value* V) {
	Value* Xor = B.CreateXor(A, V, "mba.xor");
	Value* And = B.CreateAnd(A, V, "mba.and");
	Value* Shl = B.CreateShl(And, ConstantInt::get(A->getType(), 1), "mba.shl");
	return B.CreateAdd(Xor, Shl, "mba.add");
}

// x + y  =>  (x | y) + (x & y)
Value* MbaUtils::addAlt(IRBuilder<>& B, Value* A, Value* V) {
	Value* Or = B.CreateOr(A, V, "mba.or");
	Value* And = B.CreateAnd(A, V, "mba.and");
	return B.CreateAdd(Or, And, "mba.add.alt");
}

// x + y  =>  2*(x | y) - (x ^ y)    [used by VM pass hardener]
Value* MbaUtils::addAlt2(IRBuilder<>& B, Value* A, Value* V) {
	Value* Or = B.CreateOr(A, V, "mba.or");
	Value* Shl = B.CreateShl(Or, ConstantInt::get(A->getType(), 1), "mba.shl");
	Value* Xor = B.CreateXor(A, V, "mba.xor");
	return B.CreateSub(Shl, Xor, "mba.add.alt2");
}

// x + y  =>  (x - ~y) - 1
Value* MbaUtils::addAlt3(IRBuilder<>& B, Value* A, Value* V) {
	Value* NotV = B.CreateNot(V, "mba.add.alt3.not");
	Value* Sub = B.CreateSub(A, NotV, "mba.add.alt3.sub");
	return B.CreateSub(Sub, ConstantInt::get(A->getType(), 1), "mba.add.alt3");
}

// ============================================================================
// Core Value-level transforms — Sub
// ============================================================================

// x - y  =>  (x ^ y) - 2*(~x & y)
Value* MbaUtils::sub(IRBuilder<>& B, Value* A, Value* V) {
	Value* Xor = B.CreateXor(A, V, "mba.xor");
	Value* NotA = B.CreateNot(A, "mba.not");
	Value* And = B.CreateAnd(NotA, V, "mba.and");
	Value* Shl = B.CreateShl(And, ConstantInt::get(A->getType(), 1), "mba.shl");
	return B.CreateSub(Xor, Shl, "mba.sub");
}

// x - y  =>  (x & ~y) - (~x & y)
Value* MbaUtils::subAlt(IRBuilder<>& B, Value* A, Value* V) {
	Value* NotA = B.CreateNot(A, "mba.notx");
	Value* NotV = B.CreateNot(V, "mba.noty");
	Value* And1 = B.CreateAnd(A, NotV, "mba.and1");
	Value* And2 = B.CreateAnd(NotA, V, "mba.and2");
	return B.CreateSub(And1, And2, "mba.sub.alt");
}

// x - y  =>  x + ~y + 1    (two's complement identity)  [used by VM pass hardener]
Value* MbaUtils::subAlt2(IRBuilder<>& B, Value* A, Value* V) {
	Value* NotV = B.CreateNot(V, "mba.not");
	Value* Add1 = B.CreateAdd(A, NotV, "mba.anb");
	return B.CreateAdd(Add1, ConstantInt::get(A->getType(), 1), "mba.sub.alt2");
}

// x - y  =>  ~(~x + y)
Value* MbaUtils::subAlt3(IRBuilder<>& B, Value* A, Value* V) {
	Value* NotA = B.CreateNot(A, "mba.sub.alt3.not");
	Value* Add = B.CreateAdd(NotA, V, "mba.sub.alt3.add");
	return B.CreateNot(Add, "mba.sub.alt3");
}

// ============================================================================
// Core Value-level transforms — And
// ============================================================================

// x & y  =>  (x + y) - (x | y)
Value* MbaUtils::bitwiseAnd(IRBuilder<>& B, Value* A, Value* V) {
	Value* Add = B.CreateAdd(A, V, "mba.add");
	Value* Or = B.CreateOr(A, V, "mba.or");
	return B.CreateSub(Add, Or, "mba.and");
}

// x & y  =>  ~(~x | ~y)    (De Morgan)
Value* MbaUtils::bitwiseAndAlt(IRBuilder<>& B, Value* A, Value* V) {
	Value* Na = B.CreateNot(A, "mba.na");
	Value* Nb = B.CreateNot(V, "mba.nb");
	Value* Or = B.CreateOr(Na, Nb, "mba.nor");
	return B.CreateNot(Or, "mba.and");
}

// x & y  =>  (x | y) - (x ^ y)  (bit-disjoint identity)
Value* MbaUtils::bitwiseAndAlt2(IRBuilder<>& B, Value* A, Value* V) {
	Value* Or = B.CreateOr(A, V, "mba.and.alt2.or");
	Value* Xor = B.CreateXor(A, V, "mba.and.alt2.xor");
	return B.CreateSub(Or, Xor, "mba.and.alt2");
}

// ============================================================================
// Core Value-level transforms — Or
// ============================================================================

// x | y  =>  (x & y) + (x ^ y)
Value* MbaUtils::bitwiseOr(IRBuilder<>& B, Value* A, Value* V) {
	Value* And = B.CreateAnd(A, V, "mba.and");
	Value* Xor = B.CreateXor(A, V, "mba.xor");
	return B.CreateAdd(And, Xor, "mba.or");
}

// x | y  =>  (x + y) - (x & y)
Value* MbaUtils::bitwiseOrAlt(IRBuilder<>& B, Value* A, Value* V) {
	Value* Add = B.CreateAdd(A, V, "mba.add");
	Value* And = B.CreateAnd(A, V, "mba.and");
	return B.CreateSub(Add, And, "mba.or.alt");
}

// x | y  =>  (x ^ y) | (x & y)   [bitwise-OR form; disjoint bits => same result]
// Used by VM pass hardener to match its original IR pattern.
Value* MbaUtils::bitwiseOrAlt2(IRBuilder<>& B, Value* A, Value* V) {
	Value* Xor = B.CreateXor(A, V, "mba.xor");
	Value* And = B.CreateAnd(A, V, "mba.and");
	return B.CreateOr(Xor, And, "mba.or.alt2");
}

// ============================================================================
// Core Value-level transforms — Xor
// ============================================================================

// x ^ y  =>  (x | y) - (x & y)
Value* MbaUtils::bitwiseXor(IRBuilder<>& B, Value* A, Value* V) {
	Value* Or = B.CreateOr(A, V, "mba.or");
	Value* And = B.CreateAnd(A, V, "mba.and");
	return B.CreateSub(Or, And, "mba.xor");
}

// x ^ y  =>  (~x & y) | (x & ~y)
Value* MbaUtils::bitwiseXorAlt(IRBuilder<>& B, Value* A, Value* V) {
	Value* NotA = B.CreateNot(A, "mba.notx");
	Value* NotV = B.CreateNot(V, "mba.noty");
	Value* And1 = B.CreateAnd(NotA, V, "mba.and1");
	Value* And2 = B.CreateAnd(A, NotV, "mba.and2");
	return B.CreateOr(And1, And2, "mba.xor.alt");
}

// x ^ y  =>  (x | y) & ~(x & y)
Value* MbaUtils::bitwiseXorAlt2(IRBuilder<>& B, Value* A, Value* V) {
	Value* Or = B.CreateOr(A, V, "mba.xor.alt2.or");
	Value* And = B.CreateAnd(A, V, "mba.xor.alt2.and");
	Value* NotAnd = B.CreateNot(And, "mba.xor.alt2.not");
	return B.CreateAnd(Or, NotAnd, "mba.xor.alt2");
}

// ============================================================================
// Core Value-level transforms — Mul
// ============================================================================

// x * y
Value* MbaUtils::mul(IRBuilder<>& B, Value* A, Value* V) {
	return B.CreateMul(A, V, "mba.mul");
}

// x * y  =>  -((-x) * y)
Value* MbaUtils::mulAlt(IRBuilder<>& B, Value* A, Value* V) {
	Value* NegA = B.CreateNeg(A, "mba.mul.alt.negx");
	Value* Mul = B.CreateMul(NegA, V, "mba.mul.alt.mul");
	return B.CreateNeg(Mul, "mba.mul.alt");
}

// x * y  =>  x*(y & 0xFFFF) + (x * (y >>> 16)) << 16    (16-bit split-mul; mod 2^32)
// Distinct from mulAlt: reconstructs y from its low/high 16-bit halves so the
// per-half products differ structurally instead of being a Neg-Mul-Neg mirror.
// Only meaningful for i32 (or wider); if you call this with i8/i16, the shift
// amount of 16 would be UB — assert bitwidth >= 32.
Value* MbaUtils::mulAlt2(IRBuilder<>& B, Value* A, Value* V) {
	Type* T = A->getType();
	unsigned BW = T->getScalarSizeInBits();
	assert(BW >= 32 && "mulAlt2 split-mul requires bitwidth >= 32");
	Constant* LoMask = ConstantInt::get(T, 0xFFFFu);
	Constant* Sixteen = ConstantInt::get(T, 16);
	Value* YLo = B.CreateAnd(V, LoMask, "mba.mul.alt2.ylo");
	Value* YHi = B.CreateLShr(V, Sixteen, "mba.mul.alt2.yhi");
	Value* MLo = B.CreateMul(A, YLo, "mba.mul.alt2.mlo");
	Value* MHi = B.CreateMul(A, YHi, "mba.mul.alt2.mhi");
	Value* MHiShift = B.CreateShl(MHi, Sixteen, "mba.mul.alt2.mhishl");
	return B.CreateAdd(MLo, MHiShift, "mba.mul.alt2");
}

// ============================================================================
// Core Value-level transforms — Shl
// ============================================================================

// x << n   (n must be ConstantInt)
Value* MbaUtils::shl(IRBuilder<>& B, Value* A, Value* N) {
	return B.CreateShl(A, N, "mba.shl");
}

// x << n  =>  x * (1 << n)     [n const]
Value* MbaUtils::shlAlt(IRBuilder<>& B, Value* A, Value* N) {
	auto* CI = cast<ConstantInt>(N);
	unsigned NVal = (unsigned)CI->getZExtValue();
	Type* T = A->getType();
	Constant* Pow = ConstantInt::get(T, APInt(T->getScalarSizeInBits(), 1) << NVal);
	return B.CreateMul(A, Pow, "mba.shl.alt");
}

// x << n  =>  ~((~x) << n) - ((1 << n) - 1)   [n const]
Value* MbaUtils::shlAlt2(IRBuilder<>& B, Value* A, Value* N) {
	auto* CI = cast<ConstantInt>(N);
	unsigned NVal = (unsigned)CI->getZExtValue();
	Type* T = A->getType();
	unsigned BW = T->getScalarSizeInBits();
	Value* NotA = B.CreateNot(A, "mba.shl.alt2.notx");
	Value* Shifted = B.CreateShl(NotA, N, "mba.shl.alt2.shl");
	Value* NotShifted = B.CreateNot(Shifted, "mba.shl.alt2.not");
	// (1 << n) - 1 as constant of the same type. For NVal == 0, mask == 0.
	APInt MaskAP = NVal == 0 ? APInt(BW, 0) : APInt::getLowBitsSet(BW, NVal);
	Constant* Mask = ConstantInt::get(T, MaskAP);
	return B.CreateSub(NotShifted, Mask, "mba.shl.alt2");
}

// ============================================================================
// BinaryOperator-level wrappers (bump STATISTIC counters)
// ============================================================================

Value* MbaUtils::applyPrimary(IRBuilder<>& B, BinaryOperator* BO) {
	if (!BO) return nullptr;
	Value* A = BO->getOperand(0);
	Value* V = BO->getOperand(1);
	switch (BO->getOpcode()) {
	case Instruction::Add: ++MBAAdd; return add(B, A, V);
	case Instruction::Sub: ++MBASub; return sub(B, A, V);
	case Instruction::And: ++MBAAnd; return bitwiseAnd(B, A, V);
	case Instruction::Or:  ++MBAOr;  return bitwiseOr(B, A, V);
	case Instruction::Xor: ++MBAXor; return bitwiseXor(B, A, V);
	default:               return nullptr;
	}
}

Value* MbaUtils::applyAlternate(IRBuilder<>& B, BinaryOperator* BO) {
	if (!BO) return nullptr;
	Value* A = BO->getOperand(0);
	Value* V = BO->getOperand(1);
	switch (BO->getOpcode()) {
	case Instruction::Add: ++MBAAdd; return addAlt(B, A, V);
	case Instruction::Sub: ++MBASub; return subAlt(B, A, V);
	case Instruction::And: ++MBAAnd; return bitwiseAndAlt(B, A, V);
	case Instruction::Or:  ++MBAOr;  return bitwiseOrAlt(B, A, V);
	case Instruction::Xor: ++MBAXor; return bitwiseXorAlt(B, A, V);
	default:               return nullptr;
	}
}

// ============================================================================
// Indexed pool access (handler-variant diversification)
// ============================================================================
// Value-level dispatch only — deliberately bypasses applyPrimary/applyAlternate
// so the MBAAdd/Sub/And/Or/Xor STATISTIC counters stay untouched.

unsigned MbaUtils::poolSize(Instruction::BinaryOps Op) const {
	switch (Op) {
	case Instruction::Add: return 4; // add, addAlt, addAlt2, addAlt3
	case Instruction::Sub: return 4; // sub, subAlt, subAlt2, subAlt3
	case Instruction::And: return 3; // bitwiseAnd, bitwiseAndAlt, bitwiseAndAlt2
	case Instruction::Or:  return 3; // bitwiseOr, bitwiseOrAlt, bitwiseOrAlt2
	case Instruction::Xor: return 3; // bitwiseXor, bitwiseXorAlt, bitwiseXorAlt2
	case Instruction::Mul: return 3; // mul, mulAlt, mulAlt2
	case Instruction::Shl: return 3; // shl, shlAlt, shlAlt2
	default:               return 0;
	}
}

Value* MbaUtils::applyByIndex(IRBuilder<>& B, Instruction::BinaryOps Op,
	Value* A, Value* V, unsigned K) {
	unsigned Size = poolSize(Op);
	if (Size == 0)
		return nullptr;

	unsigned Idx = K % Size;
	switch (Op) {
	case Instruction::Add:
		switch (Idx) {
		case 0: return add(B, A, V);
		case 1: return addAlt(B, A, V);
		case 2: return addAlt2(B, A, V);
		default: return addAlt3(B, A, V);
		}
	case Instruction::Sub:
		switch (Idx) {
		case 0: return sub(B, A, V);
		case 1: return subAlt(B, A, V);
		case 2: return subAlt2(B, A, V);
		default: return subAlt3(B, A, V);
		}
	case Instruction::And:
		switch (Idx) {
		case 0: return bitwiseAnd(B, A, V);
		case 1: return bitwiseAndAlt(B, A, V);
		default: return bitwiseAndAlt2(B, A, V);
		}
	case Instruction::Or:
		switch (Idx) {
		case 0: return bitwiseOr(B, A, V);
		case 1: return bitwiseOrAlt(B, A, V);
		default: return bitwiseOrAlt2(B, A, V);
		}
	case Instruction::Xor:
		switch (Idx) {
		case 0: return bitwiseXor(B, A, V);
		case 1: return bitwiseXorAlt(B, A, V);
		default: return bitwiseXorAlt2(B, A, V);
		}
	case Instruction::Mul:
		switch (Idx) {
		case 0: return mul(B, A, V);
		case 1: return mulAlt(B, A, V);
		default: return mulAlt2(B, A, V);
		}
	case Instruction::Shl:
		if (!isa<ConstantInt>(V)) return nullptr;
		switch (Idx) {
		case 0: return shl(B, A, V);
		case 1: return shlAlt(B, A, V);
		default: return shlAlt2(B, A, V);
		}
	default:
		return nullptr;
	}
}

// Recursive MBA: picks primary vs alternate per level using RecRng,
// recurses into newly produced BinaryOperators.
// RecRng is passed explicitly so MbaCtx::RecRng sequence is preserved 1:1.
Value* MbaUtils::applyMBARecursive(IRBuilder<>& B, BinaryOperator* BO,
	unsigned depth, Rng& RecRng) {
	if (depth == 0 || !BO)
		return BO;

	// Every MBA identity duplicates one or both operands.  Raw `undef` values
	// may choose a different bit pattern at each use, so an algebraic identity
	// that is correct for fixed bit-vectors is not necessarily correct after
	// such duplication.  Poison has the same problem and can be introduced by
	// operations that carry poison-generating flags.  Stabilize both operand
	// positions once, on the original instruction, before either the core
	// rewrite or an advanced zero builder (which reads BO's operands later)
	// gets a chance to duplicate them.
	//
	// `freeze` is a no-op for defined values and a legal refinement for
	// undef/poison.  Updating BO is intentional: addSleZero and
	// addInputDerivedZero receive the original BO after this function returns
	// and must observe these same stable values.
	for (unsigned I = 0; I < 2; ++I) {
		Value* Operand = BO->getOperand(I);
		Value* Stable = B.CreateFreeze(Operand, "mba.operand.freeze");
		BO->setOperand(I, Stable);
	}

	bool useAlt = (RecRng.range(2) != 0);
	Value* NewV = useAlt ? applyAlternate(B, BO) : applyPrimary(B, BO);

	if (!NewV || NewV == BO)
		return BO;

	// 60 % chance to recurse into the new BinaryOperator.
	if (RecRng.range(100) < 60) {
		if (auto* NewBO = dyn_cast<BinaryOperator>(NewV)) {
			IRBuilder<> NB(NewBO);
			return applyMBARecursive(NB, NewBO, depth - 1, RecRng);
		}
	}

	return NewV;
}

// ============================================================================
// Advanced inflation: inflateLinear
// ============================================================================

Value* MbaUtils::inflateLinear(IRBuilder<>& B, Value* Base, unsigned DepthHint) {
	if (!Base || !Base->getType()->isIntegerTy())
		return Base;

	AllocaInst* Slot = ensureNoiseSlot(B);
	if (!Slot)
		return Base;

	unsigned BW = cast<IntegerType>(Base->getType())->getBitWidth();
	if (BW < 2)
		return Base;

	// Depth-aware term count: halve the range when already deep to limit IR growth.
	unsigned MinT = Opts.LinearTermsMin;
	unsigned MaxT = Opts.LinearTermsMax;
	if (DepthHint >= 2) {
		MinT = std::max(4u, MinT / 2);
		MaxT = std::max(MinT, MaxT / 2);
	}

	unsigned Terms = MinT;
	if (MaxT > MinT)
		Terms = MinT + (unsigned)R.range(MaxT - MinT + 1);

	Type* Ty = Base->getType();
	Value* Cur = Base;

	// Mask RNG constants to BW bits so ConstantInt::get does not assert when
	// Ty is narrower than 32 bits (e.g. i8/i16).
	const uint64_t BWMask = (BW < 64) ? ((uint64_t(1) << BW) - 1) : ~uint64_t(0);

	for (unsigned i = 0; i < Terms; ++i) {
		Value* Z = llvm::obf::makeRuntimeZero(B, Slot, BW, R, "mba.lin0");

		// Build a term that is 0 at runtime but structurally non-trivial.
		Value* T = Z;
		switch (R.range(6)) {
		default:
		case 0: {
			// (Z | (Z << k)) -> 0 at runtime
			unsigned k = 1u + (unsigned)R.range(
				std::min(7u, BW > 1 ? BW - 1 : 1u));
			Value* Sh = B.CreateShl(Z, ConstantInt::get(Ty, k), "mba.lin.shl");
			T = B.CreateOr(Z, Sh, "mba.lin.or");
			break;
		}
		case 1: {
			// (Z & (Z + C)) -> 0 at runtime (Z == 0, so result is 0)
			uint64_t Cst = ((uint64_t)R.u32() | 1ull) & BWMask;
			Value* Add = B.CreateAdd(Z, ConstantInt::get(Ty, Cst), "mba.lin.addc");
			T = B.CreateAnd(Z, Add, "mba.lin.and");
			break;
		}
		case 2: {
			// ((Z ^ K) ^ K) -> Z -> 0 at runtime
			uint64_t K = (uint64_t)R.u32() & BWMask;
			Value* Kc = ConstantInt::get(Ty, K);
			Value* X1 = B.CreateXor(Z, Kc, "mba.lin.x1");
			T = B.CreateXor(X1, Kc, "mba.lin.x2");
			break;
		}
		case 3: {
			// (Z * oddC) -> 0 at runtime (Z == 0)
			uint64_t Cst = ((uint64_t)R.u32() | 1ull) & BWMask;
			T = B.CreateMul(Z, ConstantInt::get(Ty, Cst), "mba.lin.mulc");
			break;
		}
		case 4: {
			// ((Z + K) & Z) -> 0 at runtime
			uint64_t K = (uint64_t)R.u32() & BWMask;
			Value* Add = B.CreateAdd(Z, ConstantInt::get(Ty, K), "mba.lin.addk");
			T = B.CreateAnd(Add, Z, "mba.lin.and2");
			break;
		}
		case 5: {
			// (Z & (Z | K)) -> Z -> 0 at runtime
			uint64_t K = (uint64_t)R.u32() & BWMask;
			Value* Or = B.CreateOr(Z, ConstantInt::get(Ty, K), "mba.lin.orK");
			T = B.CreateAnd(Z, Or, "mba.lin.and3");
			break;
		}
		}

		// Accumulate using + or - (both preserve semantics since T == 0 at runtime).
		if (R.range(2))
			Cur = B.CreateAdd(Cur, T, "mba.lin.sum");
		else
			Cur = B.CreateSub(Cur, T, "mba.lin.sub");
	}

	return Cur;
}

// ============================================================================
// Advanced inflation: addNonLinearZero
// ============================================================================

// Add a nonlinear (mul / urem-based) runtime-zero to Cur.
// Uses identities where the result is exactly 0 because Z == 0 at runtime,
// but the expression is opaque to SMT solvers / instcombine.
Value* MbaUtils::addNonLinearZero(IRBuilder<>& B, BinaryOperator& Orig, Value* Cur) {
	if (!Cur || !Cur->getType()->isIntegerTy())
		return Cur;

	AllocaInst* Slot = ensureNoiseSlot(B);
	if (!Slot)
		return Cur;

	unsigned BW = cast<IntegerType>(Cur->getType())->getBitWidth();
	Type* Ty = Cur->getType();

	Value* x = Orig.getOperand(0);
	Value* y = Orig.getOperand(1);
	if (!x || !y || x->getType() != Ty || y->getType() != Ty)
		return Cur;

	Value* Z = llvm::obf::makeRuntimeZero(B, Slot, BW, R, "mba.nonlin0");

	Value* NZ = nullptr;
	switch (R.range(2)) {
	default:
	case 0: {
		// mul(x, y) - mul(x, y + Z) == 0 at runtime  (Z == 0)
		Value* t1 = B.CreateMul(x, y, "mba.nl.mul1");
		Value* y2 = B.CreateAdd(y, Z, "mba.nl.y2");
		Value* t2 = B.CreateMul(x, y2, "mba.nl.mul2");
		NZ = B.CreateSub(t1, t2, "mba.nl.zero");
		break;
	}
	case 1: {
		// urem(x*C, M) - urem((x+Z)*C, M) == 0 at runtime  (Z == 0)
		static constexpr uint32_t Mods[] = { 251u, 509u, 1009u, 4093u };
		uint32_t M = Mods[(size_t)R.range(
			(uint32_t)(sizeof(Mods) / sizeof(Mods[0])))];
		uint32_t C = (R.u32() | 1u);

		// Mask to BW so ConstantInt::get does not assert on narrow Ty (i1/i8).
		const uint64_t BWMask = (BW < 64) ? ((uint64_t(1) << BW) - 1) : ~uint64_t(0);
		uint64_t Mm = (uint64_t)M & BWMask;
		if (Mm == 0) Mm = 1; // urem by 0 is UB
		uint64_t Cm = ((uint64_t)C | 1ull) & BWMask;
		if (Cm == 0) Cm = 1;

		Value* Mc = ConstantInt::get(Ty, Mm);
		Value* Cc = ConstantInt::get(Ty, Cm);

		Value* t1 = B.CreateURem(B.CreateMul(x, Cc, "mba.nl.m1"), Mc, "mba.nl.r1");
		Value* x2 = B.CreateAdd(x, Z, "mba.nl.x2");
		Value* t2 = B.CreateURem(B.CreateMul(x2, Cc, "mba.nl.m2"), Mc, "mba.nl.r2");
		NZ = B.CreateSub(t1, t2, "mba.nl.zero2");
		break;
	}
	}

	if (!NZ)
		return Cur;

	return B.CreateAdd(Cur, NZ, "mba.nl.add");
}

// ============================================================================
// Advanced inflation: addHighDegreeZero
// ============================================================================

// Add degree-4 or degree-5 polynomial runtime-zero: f(v+Z) - f(v) == 0 (Z == 0).
Value* MbaUtils::addHighDegreeZero(IRBuilder<>& B, BinaryOperator& Orig,
	Value* Cur, unsigned DepthHint) {
	if (!Cur || !Cur->getType()->isIntegerTy())
		return Cur;

	AllocaInst* Slot = ensureNoiseSlot(B);
	if (!Slot)
		return Cur;

	unsigned BW = cast<IntegerType>(Cur->getType())->getBitWidth();
	// Restrict to 32/64-bit where analysis tools typically focus.
	if (BW < 2 || (BW != 32 && BW != 64))
		return Cur;

	Type* Ty = Cur->getType();

	Value* x = Orig.getOperand(0);
	if (!x || x->getType() != Ty)
		return Cur;

	Value* Z = llvm::obf::makeRuntimeZero(B, Slot, BW, R, "mba.hd0");

	auto pow2 = [&](Value* v) { return B.CreateMul(v, v, "mba.hd.p2"); };
	auto pow3 = [&](Value* v) { return B.CreateMul(pow2(v), v, "mba.hd.p3"); };
	auto pow4 = [&](Value* v) {
		Value* v2 = pow2(v);
		return B.CreateMul(v2, v2, "mba.hd.p4");
		};
	auto pow5 = [&](Value* v) { return B.CreateMul(pow4(v), v, "mba.hd.p5"); };
	(void)pow3; // suppress unused-lambda warning; only pow4/pow5 used below

	// Base: optionally mix both operands to vary signatures across sites.
	Value* base = x;
	if (R.range(2))
		base = B.CreateAdd(x, Orig.getOperand(1), "mba.hd.base");

	Value* b0 = B.CreateFreeze(base, "mba.hd.b0");
	Value* b1 = B.CreateAdd(b0, Z, "mba.hd.b1");

	Value* f0;
	Value* f1;
	if (DepthHint >= 3 && R.range(2)) {
		f0 = pow5(b0);
		f1 = pow5(b1);
	}
	else {
		f0 = pow4(b0);
		f1 = pow4(b1);
	}

	Value* diff = B.CreateSub(f1, f0, "mba.hd.diff");
	return B.CreateAdd(Cur, diff, "mba.hd.add");
}

// ============================================================================
// Advanced inflation: addMixedModeZero
// ============================================================================

// Add a rotation + mixing + polynomial runtime-zero to Cur.
// The mixing function is non-linear over integers, increasing SMT hardness.
Value* MbaUtils::addMixedModeZero(IRBuilder<>& B, BinaryOperator& Orig,
	Value* Cur, unsigned DepthHint) {
	if (!Cur || !Cur->getType()->isIntegerTy())
		return Cur;

	AllocaInst* Slot = ensureNoiseSlot(B);
	if (!Slot)
		return Cur;

	unsigned BW = cast<IntegerType>(Cur->getType())->getBitWidth();
	if (BW < 2 || (BW != 32 && BW != 64))
		return Cur;

	Type* Ty = Cur->getType();

	Value* x = Orig.getOperand(0);
	Value* y = Orig.getOperand(1);
	if (!x || !y || x->getType() != Ty || y->getType() != Ty)
		return Cur;

	Value* Z = llvm::obf::makeRuntimeZero(B, Slot, BW, R, "mba.mm0");

	// Rotation amount: masked to 0..BW-1 to avoid poison on shift.
	Value* Amt = llvm::obf::xorWithRuntimeZero(
		B, llvm::obf::getObfEntropyI32(B), Slot, R, "mba.mm.amt", 50);
	if (Amt->getType() != Ty)
		Amt = B.CreateZExtOrTrunc(Amt, Ty, "mba.mm.amt.cast");
	Value* BWMask = ConstantInt::get(Ty, BW - 1);
	Amt = B.CreateAnd(B.CreateFreeze(Amt, "mba.mm.amt.fr"), BWMask, "mba.mm.amt.m");

	// Left-rotation helper.
	auto rotl = [&](Value* v) -> Value* {
		Value* Rv = B.CreateSub(ConstantInt::get(Ty, BW), Amt, "mba.mm.r");
		Rv = B.CreateAnd(Rv, BWMask, "mba.mm.rm");
		Value* shl = B.CreateShl(v, Amt, "mba.mm.shl");
		Value* shr = B.CreateLShr(v, Rv, "mba.mm.shr");
		return B.CreateOr(shl, shr, "mba.mm.rot");
		};

	uint64_t MixOdd = (R.u32() | 1u);

	// Mixing function: rotl(v) XOR lshr(v,13), then multiply by odd constant.
	auto mix = [&](Value* v, const char* tag) -> Value* {
		Value* r = rotl(v);
		Value* s = B.CreateLShr(v, ConstantInt::get(Ty, 13),
			(std::string(tag) + ".shr").c_str());
		Value* m = B.CreateXor(r, s, (std::string(tag) + ".x1").c_str());
		return B.CreateMul(m, ConstantInt::get(Ty, MixOdd),
			(std::string(tag) + ".mul").c_str());
		};

	Value* base = B.CreateXor(x, y, "mba.mm.base");
	Value* b0 = B.CreateFreeze(base, "mba.mm.b0");
	Value* b1 = B.CreateAdd(b0, Z, "mba.mm.b1");    // b1 == b0 at runtime (Z==0)

	Value* f0 = mix(b0, "mba.mm.f0");
	Value* f1 = mix(b1, "mba.mm.f1");

	// Optional nonlinear lift: multiply to increase polynomial degree.
	if (DepthHint >= 3) {
		f0 = B.CreateMul(f0, b0, "mba.mm.l0");
		f1 = B.CreateMul(f1, b1, "mba.mm.l1");
	}

	Value* diff = B.CreateSub(f1, f0, "mba.mm.diff");
	return B.CreateAdd(Cur, diff, "mba.mm.add");
}

// ============================================================================
// Input-derived zeros (V1) — memory-free runtime zeros
// ============================================================================
//
// Each form takes two spellings of the same value: `f`, an MBA re-spelling built
// from bitwise ops, and `g`, the plain arithmetic spelling. `f == g` for all
// inputs, so any function of them cancels: `lift(f) - lift(g) == 0`. The plain
// difference `f - g` folds instantly (it is just the base identity), but a
// *nonlinear* lift (cube / pow4 / squared product) forces the solver to bit-blast
// the bitwise-inside-multiply structure — validated to exceed a 5 s Z3 budget
// while remaining an exact ring identity mod 2^BW (any bit width).
//
// The runtime zero is an *addend* — it need not match the site's opcode, so the
// pool deliberately uses only the two MBA spellings InstCombine does NOT collapse:
//   add-spelling  (x^y)+2(x&y) == x+y      (not folded to x+y by -O2)
//   sub-spelling  (x&~y)-(~x&y) == x-y     (not folded to x-y by -O2)
// The canonical bitwise spellings ((x+y)-(x&y)==x|y, (x|y)-(x&y)==x^y,
// (x+y)-(x|y)==x&y) are AVOIDED — InstCombine rewrites f->g for those, which
// collapses lift(f)-lift(g) to 0 under an attacker's own -O2 (see mba_fold_check).
//
// Pool (7 forms), each an exact 0, Z3-timeout-strong, and -O2 fold-resistant:
//   0 add  cube:  ((x^y)+2(x&y))^3                    - (x+y)^3
//   1 sub  w2:    ((x&~y)-(~x&y))*(x|y)^2             - (x-y)*(x|y)^2
//   2 mul  prod:  [((x^y)+2(x&y))*((x|y)-(x&y))]^2    - [(x+y)*(x^y)]^2
//   3 add  pow4:  ((x^y)+2(x&y))^4                    - (x+y)^4
//   4 sub  cube:  ((x&~y)-(~x&y))^3                   - (x-y)^3
//   5 add  w2xor: ((x^y)+2(x&y))*(x^y)^2             - (x+y)*(x^y)^2
//   6 sub  pow4:  ((x&~y)-(~x&y))^4                   - (x-y)^4

unsigned MbaUtils::inputZeroPoolSize() const { return 7; }

Value* MbaUtils::inputDerivedZero(IRBuilder<>& B, Value* X, Value* Y, unsigned K) {
	if (!X || !Y)
		return nullptr;
	Type* Ty = X->getType();
	if (!Ty->isIntegerTy() || Y->getType() != Ty)
		return nullptr;
	if (Ty->getScalarSizeInBits() < 2)
		return nullptr;

	Constant* Two = ConstantInt::get(Ty, 2);
	auto Xor = [&](Value* a, Value* b) { return B.CreateXor(a, b, "mba.idz.x"); };
	auto And = [&](Value* a, Value* b) { return B.CreateAnd(a, b, "mba.idz.a"); };
	auto Or  = [&](Value* a, Value* b) { return B.CreateOr(a, b, "mba.idz.o"); };
	auto Add = [&](Value* a, Value* b) { return B.CreateAdd(a, b, "mba.idz.add"); };
	auto Sub = [&](Value* a, Value* b) { return B.CreateSub(a, b, "mba.idz.sub"); };
	auto Mul = [&](Value* a, Value* b) { return B.CreateMul(a, b, "mba.idz.mul"); };
	auto Not = [&](Value* a) { return B.CreateNot(a, "mba.idz.n"); };
	auto Sqr  = [&](Value* v) { return Mul(v, v); };
	auto Cube = [&](Value* v) { return Mul(Sqr(v), v); };
	auto Pow4 = [&](Value* v) { Value* s = Sqr(v); return Mul(s, s); };

	// Twice(v) == 2*v.
	auto Twice = [&](Value* v) { return Mul(Two, v); };

	Value* f = nullptr;
	Value* g = nullptr;
	switch (K % inputZeroPoolSize()) {
	default:
	case 0: // add, cube
		f = Add(Xor(X, Y), Twice(And(X, Y)));   // == x + y
		g = Add(X, Y);
		return Sub(Cube(f), Cube(g));
	case 1: { // sub, (x|y)^2-weighted
		f = Sub(And(X, Not(Y)), And(Not(X), Y)); // == x - y
		g = Sub(X, Y);
		Value* w = Or(X, Y);
		Value* w2 = Sqr(w);
		return Sub(Mul(f, w2), Mul(g, w2));
	}
	case 2: { // mul-shaped deep product, squared
		f = Mul(Add(Xor(X, Y), Twice(And(X, Y))), Sub(Or(X, Y), And(X, Y))); // (x+y)*(x^y)
		g = Mul(Add(X, Y), Xor(X, Y));
		return Sub(Sqr(f), Sqr(g));
	}
	case 3: // add, pow4
		f = Add(Xor(X, Y), Twice(And(X, Y)));   // == x + y
		g = Add(X, Y);
		return Sub(Pow4(f), Pow4(g));
	case 4: // sub-spelling, cube
		f = Sub(And(X, Not(Y)), And(Not(X), Y)); // == x - y
		g = Sub(X, Y);
		return Sub(Cube(f), Cube(g));
	case 5: { // add-spelling, weighted by (x^y)^2
		f = Add(Xor(X, Y), Twice(And(X, Y)));    // == x + y
		g = Add(X, Y);
		Value* w2 = Sqr(Xor(X, Y));
		return Sub(Mul(f, w2), Mul(g, w2));
	}
	case 6: // sub-spelling, pow4
		f = Sub(And(X, Not(Y)), And(Not(X), Y)); // == x - y
		g = Sub(X, Y);
		return Sub(Pow4(f), Pow4(g));
	}
}

Value* MbaUtils::addInputDerivedZero(IRBuilder<>& B, BinaryOperator& Orig,
	Value* Cur, unsigned K) {
	if (!Cur || !Cur->getType()->isIntegerTy())
		return Cur;

	Value* x = Orig.getOperand(0);
	Value* y = Orig.getOperand(1);
	Type* Ty = Cur->getType();
	if (!x || !y || x->getType() != Ty || y->getType() != Ty)
		return Cur;

	Value* NZ = inputDerivedZero(B, x, y, K);
	if (!NZ || NZ->getType() != Ty)
		return Cur;

	return B.CreateAdd(Cur, NZ, "mba.idz.acc");
}

// ============================================================================
// SLE pool (V2) — runtime-loaded, nonlinear-lifted SLE runtime zeros
// ============================================================================
//
// Pool loads once (thread-safe static init) from $XOLLVM_SLE_POOL, falling back
// to the compiled-in kSleFallbackPool (MBASlePool.inc). Each entry is
// (base, lift, 13 coeffs): the runtime zero is lift(f) - lift(g), where
// f = sum coeffs[i] * basis[i](x,y) (an SLE spelling == the base value) and
// g = the canonical base value (x+y for add, x-y for sub). Coefficients apply
// at any bit width: (c * basis) reduces mod 2^BW automatically, so the identity
// holds for i8/i16/i32/i64 alike.

namespace {

struct SleEntry {
	int base;        // 0 = add (x+y), 1 = sub (x-y)
	int lift;        // 0 = cube, 1 = pow4, 2 = prodsq (*(x^y)^2)
	int coeffs[13];  // over basis order: one x y and or xor nx ny nand nor xnor xany nxay
};

static int parseSleBase(StringRef s) { return s == "sub" ? 1 : 0; }
static int parseSleLift(StringRef s) {
	if (s == "pow4") return 1;
	if (s == "prodsq") return 2;
	return 0;
}

// Parse one pool line "<base> <lift> c0 .. c12" into E; return false on any error.
static bool parseSleLine(StringRef Line, SleEntry& E) {
	SmallVector<StringRef, 16> Tok;
	Line.split(Tok, ' ', /*MaxSplit=*/-1, /*KeepEmpty=*/false);
	if (Tok.size() < 15)
		return false;
	E.base = parseSleBase(Tok[0]);
	E.lift = parseSleLift(Tok[1]);
	for (int i = 0; i < 13; ++i) {
		long long C = 0;
		if (Tok[2 + i].getAsInteger(10, C))
			return false;
		E.coeffs[i] = (int)C;
	}
	return true;
}

static const std::vector<SleEntry>& sleActivePool() {
	static const std::vector<SleEntry> Pool = []() {
		std::vector<SleEntry> V;
		if (const char* Path = std::getenv("XOLLVM_SLE_POOL")) {
			if (auto Buf = MemoryBuffer::getFile(Path)) {
				for (line_iterator LI(**Buf, /*SkipBlanks=*/true, /*CommentMarker=*/'#');
					!LI.is_at_eof(); ++LI) {
					SleEntry E{};
					if (parseSleLine(LI->trim(), E))
						V.push_back(E);
				}
			}
		}
		if (V.empty()) {
			for (unsigned i = 0; i < kSleFallbackPoolSize; ++i) {
				const auto& FE = kSleFallbackPool[i];
				SleEntry E{};
				E.base = parseSleBase(FE.base);
				E.lift = parseSleLift(FE.lift);
				for (int j = 0; j < 13; ++j)
					E.coeffs[j] = FE.coeffs[j];
				V.push_back(E);
			}
		}
		return V;
	}();
	return Pool;
}

} // namespace

unsigned MbaUtils::slePoolSize() const {
	return (unsigned)sleActivePool().size();
}

Value* MbaUtils::addSleZero(IRBuilder<>& B, BinaryOperator& Orig, Value* Cur, unsigned K) {
	if (!Cur || !Cur->getType()->isIntegerTy())
		return Cur;

	Value* X = Orig.getOperand(0);
	Value* Y = Orig.getOperand(1);
	Type* Ty = Cur->getType();
	if (!X || !Y || X->getType() != Ty || Y->getType() != Ty)
		return Cur;
	if (Ty->getScalarSizeInBits() < 2)
		return Cur;

	const std::vector<SleEntry>& Pool = sleActivePool();
	if (Pool.empty())
		return Cur;
	const SleEntry& E = Pool[K % Pool.size()];

	auto basis = [&](int Idx) -> Value* {
		switch (Idx) {
		case 0:  return ConstantInt::getSigned(Ty, -1); // one (all-ones word)
		case 1:  return X;
		case 2:  return Y;
		case 3:  return B.CreateAnd(X, Y, "sle.and");
		case 4:  return B.CreateOr(X, Y, "sle.or");
		case 5:  return B.CreateXor(X, Y, "sle.xor");
		case 6:  return B.CreateNot(X, "sle.nx");
		case 7:  return B.CreateNot(Y, "sle.ny");
		case 8:  return B.CreateNot(B.CreateAnd(X, Y), "sle.nand");
		case 9:  return B.CreateNot(B.CreateOr(X, Y), "sle.nor");
		case 10: return B.CreateNot(B.CreateXor(X, Y), "sle.xnor");
		case 11: return B.CreateAnd(X, B.CreateNot(Y), "sle.xany");
		default: return B.CreateAnd(B.CreateNot(X), Y, "sle.nxay");
		}
		};

	// f = sum coeffs[i] * basis(i)  (== base value)
	Value* f = nullptr;
	for (int i = 0; i < 13; ++i) {
		int C = E.coeffs[i];
		if (C == 0)
			continue;
		Value* BV = basis(i);
		Value* Term = (C == 1)
			? BV
			: B.CreateMul(ConstantInt::getSigned(Ty, C), BV, "sle.cmul");
		f = f ? B.CreateAdd(f, Term, "sle.acc") : Term;
	}
	if (!f)
		return Cur;

	Value* g = (E.base == 1) ? B.CreateSub(X, Y, "sle.g")
		: B.CreateAdd(X, Y, "sle.g");

	auto lift = [&](Value* v) -> Value* {
		if (E.lift == 0) { // cube
			Value* s = B.CreateMul(v, v, "sle.l2");
			return B.CreateMul(s, v, "sle.l3");
		}
		if (E.lift == 1) { // pow4
			Value* s = B.CreateMul(v, v, "sle.l2");
			return B.CreateMul(s, s, "sle.l4");
		}
		// prodsq: (v * (x^y))^2
		Value* w = B.CreateXor(X, Y, "sle.w");
		Value* p = B.CreateMul(v, w, "sle.p");
		return B.CreateMul(p, p, "sle.psq");
		};

	Value* NZ = B.CreateSub(lift(f), lift(g), "sle.zero");
	if (NZ->getType() != Ty)
		return Cur;

	return B.CreateAdd(Cur, NZ, "sle.add");
}

// ============================================================================
// Layered MBA window
// ============================================================================

void MbaUtils::applyLayeredWindow(Instruction* Anchor, Instruction* Skip,
	unsigned DepthHint, Rng& RecRng) {
	if (!Opts.EnableLayered || Opts.LayeredBudget == 0 || Opts.LayeredWindow == 0)
		return;
	if (!Anchor)
		return;

	BasicBlock* BB = Anchor->getParent();
	if (!BB)
		return;

	// Collect eligible BinaryOperators in reverse instruction order
	// (newest-first, i.e. from Anchor backward).
	SmallVector<BinaryOperator*, 64> Cands;
	unsigned Seen = 0;
	for (Instruction* I = Anchor->getPrevNode();
		I && Seen < Opts.LayeredWindow;
		I = I->getPrevNode(), ++Seen) {
		if (I == Skip)
			continue;
		auto* BO = dyn_cast<BinaryOperator>(I);
		if (!BO)
			continue;
		if (!isTargetOpcode(BO->getOpcode()))
			continue;
		if (hasPoisonSensitiveFlags(*BO))
			continue;
		if (!BO->getType()->isIntegerTy())
			continue;
		// Avoid aggressively exploding deeper layers.
		Cands.push_back(BO);
	}

	if (Cands.empty())
		return;

	unsigned Budget = std::min<unsigned>(Opts.LayeredBudget,
		(unsigned)Cands.size());

	for (unsigned i = 0; i < Budget; ++i) {
		BinaryOperator* BO = Cands[i];
		if (!BO || BO->getParent() != BB)
			continue;

		IRBuilder<> B(BO);
		// One-step recursive rewrite (DepthHint influences inflation).
		Value* V = applyMBARecursive(B, BO, /*depth=*/1, RecRng);
		if (!V || V == BO)
			continue;

		V = inflateLinear(B, V, DepthHint + 1);
		BO->replaceAllUsesWith(V);
		BO->eraseFromParent();
		// B's insert point is now invalid; the next iteration creates a fresh one.
	}
}
